config/routes.rb
Tagport::Application.routes.draw do

  get "/users/sign_in" => redirect('/home/come_aboard')
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  get "home/index"
  get "home/contact"
  get "home/come_aboard"
  root :to => 'home#index'

  resources :searches

end

app/models/search.rb
class Search < ActiveRecord::Base
  belongs_to :user
  
  attr_accessible :tags
  # attr_reader :tag, :excludes
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :username, :provider, :uid
  # attr_accessible :title, :body
  
  has_many :searches
  
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.username = auth.info.nickname
      user.name = auth.info.name
      
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  # removes the utf8 param from url if broswer is not IE.
  before_filter do
    @utf8_enforcer_tag_enabled = browser.ie?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @title = "Tagport | Monitor hashtags from Instagram and Twitter under one hood now."
  end

  def contact
  end
  
  def come_aboard
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def all
    user = User.from_omniauth(request.env["omniauth.auth"])
    if user.persisted?
      flash.notice = "Signed in!"
      sign_in_and_redirect user
    else
      session["devise.user_attributes"] = user.attributes
      redirect_to new_user_registration_url
    end
  end
  alias_method :twitter, :all
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def new
  end

  def index
  end

  def show
  end

  def create
    # Initializing classes
    twitter_search = TwitterSearch.new
    instagram_search = InstagramSearch.new    

      

    # Making sure @tag is never return empty
    if params[:tag].nil? == true
      @tag = params[:search]
    else
      @tag = params[:tag]
    end

    # Setting search tag to filter results accordingly.
    @exclude = params[:exclude]

    # Looking to see if tag returns nil. If so it looks for the search params. Helps for the first load, since tag has not been set then and rest of the calls are done via ajax.
    if params[:tag].nil? == false
      @twitter_results = twitter_search.first_query(:tag => params[:tag], :count => 20, :max_id => params[:twitter_last_id]).results 
      @instagram_results = instagram_search.query(:tag => params[:tag], :count => 20, :max_tag_id => params[:instagram_max_tag_id])
    else
      # This where the first load goes. Since params[:search] is coming from the form itself.
      @twitter_results = twitter_search.first_query(:tag => params[:search], :count => 20).results
      @instagram_results = instagram_search.query(:tag => params[:search], :count => 20)
    end

    # Deleting results which pass the condition of having a text of any kind in a tweet or instagram caption
    if params[:exclude].empty? ==true
      @twitter_results
      @instagram_results
    else
      @twitter_results.delete_if{|n| n.text.include?(params[:exclude])}
      @instagram_results.delete_if{|p| p.caption.text.include?(params[:exclude]) }
    end


    # Making calls via ajax
    respond_to do |format|
      format.js {render :content_type => "text/javascript"}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Including dates helper
  include ActionView::Helpers::DateHelper
  
  def title
    base_title = "TagPort"
    return base_title if @title.nil?
    return "#{@title} | #{base_title}"
  end
  
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
  
  # Converting links in text as hyperlins and hyperlinking the twitter/instagram mentions accordingly. A little messy but works neat ;)

  def cust_link_twitter(text)
    text.gsub(/((https?:\/\/|www\.)([-\w\.]+)+(:\d+)?(\/([\w\/_\.]*(\?\S+)?)?)?)/, %Q{<a href="\\1", class="custom", target="_blank">\\1</a>}).gsub(/@(\w+)/, %Q{<a href="http://twitter.com/\\1", class="custom", target="_blank">@\\1</a>}).html_safe
  end
  
  def cust_link_instagram(text)
    text.gsub(/@(\w+)/, %Q{<a href="http://instagram.com/\\1", target="_blank">@\\1</a>}).html_safe
  end

end

app/views/home/come_aboard.html.erb
<div class="container">

	<!-- Page header -->
	<div class="page-header">
		<h2><%= @title="Come aboard"%>	</h2>
	</div>
	<!-- End of Page Header -->

	<!-- Page Content Row-->
	<div class="row">
		<!-- Start of Span8 -->
		<div class="span8">
			<div class="well">				  
				<%= form_for("user", :url => user_session_path) do |f| %>
				<fieldset>
					<div id="legend">
						<legend class="">Sign in</legend>
					</div>
					<div class="control-group">
						<!-- Username -->
						<label class="control-label"  for="email">Email</label>
						<div class="controls">
							<%= f.text_field :email, :class=>"input-xlarge"%>
						</div>
					</div>


					<div class="control-group">
						<!-- Password-->
						<label class="control-label" for="password">Password</label>
						<div class="controls">
							<%= f.password_field :password, :class=>"input-xlarge" %>
						</div>
					</div>


					<div class="control-group">
						<!-- Button -->
						<div class="controls">
							<%= f.submit 'Sign in', :class=>"btn btn-success" %>
						</div>
					</div>
				</fieldset>
				<% end %>
			</div>
		</div>
		<!-- End of Span8 -->

		<!-- Start of Span4-->
		<div class ="span4">
			<div class="well">
				<div id="legend">
					<legend class="">Sign up</legend>
				</div>
				<a href="/users/auth/twitter" class="zocial twitter">Sign up with Twitter</a>
			</div>
		</div>
		<!-- End of Span4-->
	</div>
	<!-- End of Page Content Row-->

app/views/home/contact.html.erb
<div class="container">
	<div class="page-header">
		<h2><%= @title="Contact"%>	</h2>
	</div>
	<div class="row">
		<div class="span12 pagination-centered">
			<div class="well">
				<h3>
					Feel free to get in touch with me at <a href="mailto:its@shayon.me">its@shayon.me</a> for any feedback or questions you may have ;).
				</h3>
			</div>
		</div>
	</div>

app/views/home/index.html.erb
<style>
h1 {
	color: #fff;
	font-size: 68.5px;
}
h3 {
	color: #fff;
}

</style>
<div class="full-slider">
	<div class="container">
		<div class="row-fluid">
			<div class="span12 hidden-phone">
				<h1> Welcome to TagPort !</h1>
				<p> Monitor hashtags from Instagram and Twitter under one hood now.</p>
			</div>
			<div class="span12 visible-phone">
				<h3> Welcome to TagPort !</h3>
				<h3>  Monitor hashtags from Instagram and Twitter under one hood now.</h3> 
			</div>
		</div>
	</div>
</div>

<div class="container">	
	
	<div class="page-header">
		<h2>Start your search</h2>
	</div>
	<div class="row">
		<div class="span12">
			<div class="well">		
				<!-- Passing the search query to /searches -->
				<%= form_tag searches_path, :method => :get, :class=>"form-inline", :id=>"validateForm" do %>
				<%=text_field_tag 'search', nil, :placeholder => 'Search one tag at a time. For example - beaches',:class=>"span10"%>
				<%= button_tag(:type => 'submit', :class => 'btn btn-primary') do %>
				<i class="icon-search icon-large" style="color:white"></i>
				<% end %>
				<% end %>

			</div>
		</div>
	</div>
	
<!-- Custom js method go here.-->
<%=	javascript_include_tag "search_index_path_custom"%>

app/views/layouts/_footer.html.erb
<hr>
<footer>
	<div class="span12 pagination-centered">
		Made by <a href="http://twitter.com/shayonj">@shayonj</a>. Project hosted on <a href="https://github.com/shayonj/TagPort">github</a>.
		<br \><br \>
		<a rel="license" href="http://creativecommons.org/licenses/by-nc/3.0/deed.en_US"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc/3.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">TagPort</span> by <span xmlns:cc="http://creativecommons.org/ns#" property="cc:attributionName"><a href="http://github.com/shayonj" target="_blank">shayonj</a></span> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/3.0/deed.en_US">Creative Commons Attribution-NonCommercial 3.0 Unported License</a>.

<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	ga('create', 'UA-40152792-1', 'wrkb.in');
	ga('send', 'pageview');

</script>
	</div>
</footer>

app/views/layouts/_nav.html.erb
<!-- Page Navbar -->
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="brand" href="/">TagPort</a>
			<div class="navbar-content">
				<ul class="nav  pull-right">
					<li>
						<%if user_signed_in?%>
						<a> Hi, <%=current_user.name.split(' ').first %></a>
						<%end%>
					</li>
					<li>
						<%= link_to "Home", root_path%>
					</li>
					<li>
						<%= link_to "Contact", home_contact_path%>
					</li>
					<li>
						<%if user_signed_in?%>
						<li><%= link_to "Sign out", destroy_user_session_path %></li>	
						<%else%>
						<%= link_to('Come aboard', new_user_session_path)  %>  
						<%end%>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>
<!-- End of Page Navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<title><%= title %></title>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<%if current_page?(root_path) %>
		<meta name="description" content="Monitor hashtags from Instagram and Twitter under one hood now.">
	<%elsif current_page?(:controller => "home", :action => "contact")%>
		<meta name="description" content="Contact me to know more or help on tagport">
	<%elsif current_page?(:controller => "home", :action => "come_aboard")%>
		<meta name="description" content="Join Tagport to to enjoy the premium features of the app.">
	<%elsif current_page?(searches_path)%>
		<meta name="description" content="Search for hashtags from twitter and instagram">
	<%end%>
	<meta name="keywords" content="twitter,instagram,hashtags,monitor">
	<meta name="author" content="Shayon Mukherjee">
	<meta name="google-site-verification" content="MCYFlxPaSDdl_zxdJQxx_yjpGfAX7CuTsMN1lJxLe7E" />
	<%= stylesheet_link_tag "application", "http://fonts.googleapis.com/css?family=Josefin+Slab:400,700", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<!-- Padding from top. Twitter bootstrap thingy.-->
	<style>
	body { padding-top: 40px; }
	</style>

<!-- Calling off the fancybox. Mostly for the Instagram results.-->
<script type="text/javascript">
$(document).ready(function() {
	$(".fancybox").fancybox();
});
</script>

</head>
<body>
	<!-- Rendering the navbar here.-->
	<%= render 'layouts/nav'%>

	<!-- Checking to see if notice is true. If true then display the notice and/or alert.-->
	<% if notice %>
	<div class="alert">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<%= notice %>
	</div>
	<%end%>
	<% if alert %>
	<div class="alert">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<%= alert %>
	</div>
	<%end%>

	<!-- The yield goes here-->
	<%= yield %>

	<%= render 'layouts/footer'%>
</div>
</body>
</html>

app/views/searches/_results.html.erb
<!-- Wrapping up the text in p tags. Sometimes it messes up the layout-->
<style>
.wrap {
	word-wrap: break-word;
}
a.custom:link {color: #ffffff ; font-weight: bold; text-decoration:underline;}
a.custom:visited {color: #ffffff ; font-weight: bold; text-decoration:underline;}

.custom {
	color: #fff;
	font-weight: bold; 
	text-decoration:underline;
}
</style>

<% @twitter_results.each do |s|%>
		<li>			
			<div class="<%= cycle("tweetOne","tweetTwo","tweetThree") %>">

				<span style="padding:10px"><b><u> <%=s.from_user%>:</u></b></span>

				<%= link_to "http://twitter.com/#{s.from_user}",:target => "_blank" do %>
				<%= image_tag(s.profile_image_url, :size=>"50x50", :class=>"img-circle", :style=>"float:left") %>
				<% end %>

				<br \>
				&nbsp;&nbsp;
				<%=cust_link_twitter(s.text)%>
			</div>
				<div class="row-fluid">
				  <div class="span5">
					<%="#{time_ago_in_words(s.created_at).capitalize} ago"%>
				  </div>
				  <div class="span5">
				  	<div class="pull-right">By: <u><%= link_to s.from_user,"http://twitter.com/#{s.from_user}", :target => "_blank" %></u></div>
				  </div>
			</div>
				
		</li>
<%end%>


<%@instagram_results.each do |p| %> 
<li>
	<%if p.caption == nil%>
	<!--Do nothing. Skip.-->
	<%else%>

	<%= link_to "#{p.images.standard_resolution.url}",:class => "fancybox", :title => "#{p.caption.text}" do %>
	<%= image_tag p.images.standard_resolution.url, :size=>"400x250"%>
	<%end%>
	<br \>

	<p class ="wrap"><%=cust_link_instagram(p.caption.text)%></p>

	<br \>
	<div class="row-fluid">
		<div class="span5">
			<%="#{time_ago_in_words(Time.at(p.caption.created_time.to_i)).capitalize} ago"%>
		</div>

		<div class="span5">
			<div class="pull-right">By: <u><%= link_to p.caption.from.username,"http://instagram.com/#{p.caption.from.username}", :target => '_blank' %></u></div>
		</div>
	</div>

	<%end%>
</li>
<%end%>

app/views/searches/_twitter_view.html.erb
<!-- Wrapping up the text in p tags. Sometimes it messes up the layout-->
<style>
.wrap {
	word-wrap: break-word;
}
a.custom:link {color: #ffffff ; font-weight: bold; text-decoration:underline;}
a.custom:visited {color: #ffffff ; font-weight: bold; text-decoration:underline;}

.custom {
	color: #fff;
	font-weight: bold; 
	text-decoration:underline;
}
</style>

<% @twitter_results.each do |s|%>
		<li>			
			<div class="<%= cycle("tweetOne","tweetTwo","tweetThree") %>">

				<span style="padding:10px"><b><u> <%=s.from_user%>:</u></b></span>

				<%= link_to "http://twitter.com/#{s.from_user}",:target => "_blank" do %>
				<%= image_tag(s.profile_image_url, :size=>"50x50", :class=>"img-circle", :style=>"float:left") %>
				<% end %>

				<br \>
				&nbsp;&nbsp;
				<%=cust_link_twitter(s.text)%>
			</div>
				<div class="row-fluid">
				  <div class="span5">
					<%="#{time_ago_in_words(s.created_at).capitalize} ago"%>
				  </div>
				  <div class="span5">
				  	<div class="pull-right">By: <u><%= link_to s.from_user,"http://twitter.com/#{s.from_user}", :target => "_blank" %></u></div>
				  </div>
			</div>
				
		</li>
<%end%>

app/views/searches/create.js.erb
//  Twitter results starts to populate here and checks if end of the result/pagination has been reached
<% if @twitter_results.last.id == @twitter_results.first.id%>
	$("#myModal").modal("toggle");

<% elsif @instagram_results.pagination.next_max_tag_id.nil? %>
	
<%else%>
$("div.results").append("<%= escape_javascript (render :partial => 'results') %>");
<%end%>

/*
* Running the ajax call here. Things that happen here are
*
* Layout for the view gets created using wookmark
* Auto scroll instead of pagination
*
*/

$(document).ready(new function() {
	// Prepare layout options.
	var options = {
		autoResize: true, // This will auto-update the layout when the browser window is resized.
		container: $('#main'), // Optional, used for some extra CSS styling
		offset: 5, // Optional, the distance between grid items
		itemWidth: 260 // Optional, the width of a grid item
	};

	// Get a reference to your grid items.
	var handler = $('#tiles li');

	// Call the layout function.
	handler.wookmark(options);

	// Update the layout.
	handler.wookmark();


	function loadMore()
	{ 
		$("div.load").show();
		{
			$.ajax({
				url: "<%=searches_path%>",
				method: "post",
				data: {
					tag : "<%=@tag%>",
					exclude	 : "<%=@exclude%>",
					twitter_last_id :  "<%= @twitter_results.last.id %>",
					instagram_max_tag_id :  "<%= @instagram_results.pagination.next_max_tag_id %>"
				},
				success: function(html)
				{
					if(html)
					{	    

						
						}else
						{
							$("div.load").hide();
						}
					}
				});
			}
		}

		function bindScroll(){
			if($(window).scrollTop() + $(window).height() > $(document).height() - 150) {
				$(window).unbind('scroll');
				loadMore();
			}
		}
		$(window).scroll(bindScroll);	
	});

app/views/searches/index.html.erb
<style>
.input-prepend .add-on{
	color:#d9230f;
}
</style>
<!-- Setting up the title of the page based on the searched tag-->
<%@title = "Search"%>
<!--Container loads here-->
<div class="container">
	<div class="page-header">
		<h2>Start your search</h2>
	</div>
	<!-- Search form goes here. Submitting via ajax.-->
	<div class="row">
		<div class="span12">
 			
			<div class="well">
				<%= form_tag searches_path, :method => "post", :class=>"form-inline", :name=>"extLoad", :id=>"validateForm", :remote=> true  do %>	
				<div class="input-prepend">
				<span class="add-on">#</span>	
					<!-- If the search is being done from, /search, form is left as it is-->	
					<% if params[:search].nil? == true%>
					<%=text_field_tag 'search', nil, :placeholder => 'Search for one keyword at a time (eg- holi, mumbai, newyork)' ,:class=>"span5"%>
				</div>
					<%=text_field_tag 'exclude', nil, :placeholder => 'Exclude results with a specific term: (eg- #chicago, diwali, #HotShot)' ,:class=>"span5"%>
				
				<!-- If the search is being done from /home, form is set with the search value and is being submitted through the below js code.-->	
				<%else%>
					<%=text_field_tag 'search', nil, :value => params[:search],:class=>"span5",:placeholder => 'Search for one keyword at a time (eg- holi, mumbai, newyork)'%>
					</div>
					<%=text_field_tag 'exclude', nil, :value => params[:exclude],:class=>"span5",:placeholder => 'Exclude results with a specific term: (eg- #chicago, diwali, #HotShot)'%>
				<%end%> 

				<%= button_tag(:type => 'submit', :class => 'btn btn-primary' , :id => "submitLoad") do %>
				<i class="icon-search icon-large" style="color:white"></i>
				<% end %>
				<% end %>
				
			</div>
		</div>
	</div>

	<!-- Content for twitter and Instagram gets replaced here-->
	<div id="main" role="main">
		<ul id="tiles">
			<div class="results"></div>
		</ul>
	</div>


	<!-- TagPort loader starts here.-->		
	<div class="span3 offset4 load">
		<div id="fountainTextG_1" class="fountainTextG">T</div>
		<div id="fountainTextG_2" class="fountainTextG">a</div>
		<div id="fountainTextG_3" class="fountainTextG">g</div>
		<div id="fountainTextG_4" class="fountainTextG">P</div>
		<div id="fountainTextG_5" class="fountainTextG">o</div>
		<div id="fountainTextG_6" class="fountainTextG">r</div>
		<div id="fountainTextG_7" class="fountainTextG">t</div>
	</div>
	<!-- TagPort loader ends here.-->		

<!-- Custom js method go here.-->
<%=	javascript_include_tag "search_index_path_custom"%>


		<!-- Submitting form when querying from the home page, along with the spinner firing off-->
		<% if params[:search].nil? == true%>
		<%else%>
		<script>
		$(document).ready(function () {
			$(extLoad).submit();

			$("div.load").show();

			setTimeout(function() {
				$("div.load").hide();

				}, 3000);
			});
			</script>
			<%end%>
	</div>
	
	<!-- Button to trigger modal -->

	<!-- Modal -->
	<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	  <div class="modal-header">
	    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
	    <h3 id="myModalLabel">The end has come</h3>
	  </div>
	  <div class="modal-body">
	    <p>End of twitter results. If there are any Instagram results it will be shown ;).</p>
	  </div>
	  <div class="modal-footer">
	    <button id="modalButton" class="btn" data-dismiss="modal" aria-hidden="true" >Alright Alright !</button>
	  </div>
	</div>
	
	<script>

        $("#modalButton").click( function()
           {
			 $("#myModal").hide();
             $("div.load").hide();
           }
        );
    </script>
 

app/views/searches/new.html.erb
<h1>Searches#new</h1>
<p>Find me in app/views/searches/new.html.erb</p>

app/views/searches/show.html.erb
<h1>Searches#show</h1>
<p>Find me in app/views/searches/show.html.erb</p>